apiVersion: apps/v1
kind: Deployment
metadata:
  name: development-starter
  labels:
    app: development-starter
  namespace: default
spec:
  replicas: 2
  selector:
    matchLabels:
      app: development-starter
  template:
    metadata:
      labels:
        app: development-starter
    spec:
      imagePullSecrets:
      - name: gitlab-registry-secret
      containers:
      - name: development-starter-container
        image: __IMAGE_NAME_PLACEHOLDER__:__IMAGE_TAG_PLACEHOLDER__
        ports:
        - containerPort: 3000
        resources:
          requests:
            memory: "64Mi"
            cpu: "250m"
          limits:
            memory: "128Mi"
            cpu: "500m"
        env:
        - name: NODE_ENV
          value: "development"